---

# Развертывание структуры базы данных


 - hosts: dbservers
   vars:
     sqlscripts_path: /home/mike/Projects/billing/sql

   tasks:

   - name: ensure pgsql running
     service: name=postgresql state=started

   - name: drop databse if exists and create new one
     shell: psql < {{ sqlscripts_path }}/drop-create-db.sql
     become: true
     become_user: postgres

   - name: create tables
     shell: psql < {{ sqlscripts_path }}/create-tables.sql
     become: true
     become_user: postgres

